name: kupe
description: Kupe Flutter Mobil Uygulamasi

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  google_maps_flutter: ^1.0.6
  modal_progress_hud: ^0.1.3
  animated_text_kit: ^3.1.0
  location: ^3.2.1
  # Use with FlutterLocalNotificationsPlugin class for local push notifications.
  flutter_local_notifications: ^3.0.2
  splashscreen: ^1.3.5
  # for network requests such as fetching data from a JSON
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - images/




