name: kupe
description: Kupe Flutter Mobil Uygulamasi

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  google_maps_flutter: ^1.0.6
  font_awesome_flutter: ^8.10.0
  modal_progress_hud: ^0.1.3
  animated_text_kit: ^2.5.4
  location: ^3.0.1
  # Use with FlutterLocalNotificationsPlugin class for local push notifications.
  flutter_local_notifications: ^1.4.4+1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - images/




